### ISSUE TITLE
GDPR compliance: Users need to agree to privacy policy.

### ISSUE THREAD

**Issue by nise** [michaelweiss/Pasture#26]
Since we are processing personal data of European citizens we must implement the GDPR.
As a first step on that way all registered users and all new users must agree to the privacy policy provided by the conference chairs. 
See my draft privacy policy for EuroPLoP [here](https://docs.google.com/document/d/1PVsyep94_9TpPfrehMkKOUYAX3ZaR7fCQAP6l7squlk/edit).

**Comment by michaelweiss** [comment]
Summary of the changes:
1. New users need to agree to the privacy policy before they can use the system
2. Existing users will be asked to agree to the privacy policy after they log in for the first time after the update
3. Every page contains a link to the privacy policy
